version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - sspage_network
    volumes:
      - /home/ssunuu114/nginx.conf:/etc/nginx/nginx.conf
      - sspage_static:/data/static/
      - sspage_media:/data/media/
      - sspage_log:/var/log/nginx/

  django:
    image: sspageself:05
    networks:
      - sspage_network
    volumes:
      - sspage_media:/home/self_django/media
      - sspage_static:/home/self_django/staticfiles
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - sspage_network
    volumes:
      - sspage_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  sspage_network:

volumes:
  sspage_static:
  sspage_media:
  sspage_mariadb:
  sspage_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true